# Generated by Django 4.1.6 on 2023-02-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_couponcode_product_coupon_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
