# Generated by Django 4.1.6 on 2023-02-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_couponcode_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('eligible_total', models.IntegerField()),
                ('total_saved', models.IntegerField()),
            ],
        ),
    ]
