# Generated by Django 4.1.6 on 2023-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.ManyToManyField(blank=True, to='products.deal'),
        ),
    ]
