# Generated by Django 4.1.6 on 2023-02-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='eligible_total',
            new_name='eligible_quantity',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='total_saved',
            new_name='saved_quantity',
        ),
    ]
