# Generated by Django 4.1.6 on 2023-02-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_eligible_total_deal_eligible_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
    ]
